[build]
  # Directory to publish (must contain index.html)
  publish = "dist"
  # Command to run the build
  command = "pnpm build"
  # Directory for Netlify serverless functions
  functions = "netlify/functions"


[functions]
  # Use esbuild for bundling serverless functions
  node_bundler = "esbuild"

[dev]
  targetPort = 8080

[[redirects]]
  # Redirect API calls to Netlify Functions
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback to support client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200