# Netlify build and deploy settings for Next.js + TypeScript

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Serverless API route (Netlify Next.js plugin handles this automatically)
# No need for manual /api redirects

# Remove SPA fallback
# Next.js handles routing, so we do NOT need the "/* -> /index.html" redirect