# Netlify build and deploy settings for Vite + React SPA

[build]
  command = "pnpm install && pnpm build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "true"

[dev]
  framework = "vite"
  port = 8080
  targetPort = 8080

# Serverless API route
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true